// <auto-generated />
using MediaPlayerDA.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MediaPlayerDA.Migrations
{
    [DbContext(typeof(MediaPlayerDbContext))]
    [Migration("20241014190106_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediaDTO.Media", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MediaId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaylistName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MediaId");

                    b.HasIndex("PlaylistName");

                    b.ToTable("Media");
                });

            modelBuilder.Entity("MediaDTO.Playlist", b =>
                {
                    b.Property<string>("PlaylistName")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PlaylistName");

                    b.ToTable("Playlist");
                });

            modelBuilder.Entity("MediaDTO.Media", b =>
                {
                    b.HasOne("MediaDTO.Playlist", "Playlist")
                        .WithMany("MediaFiles")
                        .HasForeignKey("PlaylistName");

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("MediaDTO.Playlist", b =>
                {
                    b.Navigation("MediaFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
